function triangleTracker() {
var x = parseFloat(prompt("Enter the x value of your triangle"));
var y = parseFloat(prompt("Enter the y value of your triangle"));
var z = parseFloat(prompt("Enter the z value of your triangle"));
if((x === y) &&(y === z))
{
alert("equilateral");
} else if((y === x) || (x === z) || (y === z))
{
alert("isosceles");
} else if((x + y) <= z || (y + z) <= x || (x + z) <= y)
{
alert("Not a Triangle");
} else {
alert("scalene");
}
}
triangleTracker();
